
-- Temporarily disable FK checks while loading
IF OBJECT_ID(N'dbo.organization', N'U') IS NOT NULL ALTER TABLE dbo.[organization] NOCHECK CONSTRAINT ALL;
IF OBJECT_ID(N'dbo.program_areas', N'U') IS NOT NULL ALTER TABLE dbo.[program_areas] NOCHECK CONSTRAINT ALL;
IF OBJECT_ID(N'dbo.roles_permissions', N'U') IS NOT NULL ALTER TABLE dbo.[roles_permissions] NOCHECK CONSTRAINT ALL;
IF OBJECT_ID(N'dbo.safehouses', N'U') IS NOT NULL ALTER TABLE dbo.[safehouses] NOCHECK CONSTRAINT ALL;
IF OBJECT_ID(N'dbo.staff', N'U') IS NOT NULL ALTER TABLE dbo.[staff] NOCHECK CONSTRAINT ALL;
IF OBJECT_ID(N'dbo.partners', N'U') IS NOT NULL ALTER TABLE dbo.[partners] NOCHECK CONSTRAINT ALL;
IF OBJECT_ID(N'dbo.supporters', N'U') IS NOT NULL ALTER TABLE dbo.[supporters] NOCHECK CONSTRAINT ALL;
IF OBJECT_ID(N'dbo.social_media_posts', N'U') IS NOT NULL ALTER TABLE dbo.[social_media_posts] NOCHECK CONSTRAINT ALL;
IF OBJECT_ID(N'dbo.partner_assignments', N'U') IS NOT NULL ALTER TABLE dbo.[partner_assignments] NOCHECK CONSTRAINT ALL;
IF OBJECT_ID(N'dbo.residents', N'U') IS NOT NULL ALTER TABLE dbo.[residents] NOCHECK CONSTRAINT ALL;
IF OBJECT_ID(N'dbo.users', N'U') IS NOT NULL ALTER TABLE dbo.[users] NOCHECK CONSTRAINT ALL;
IF OBJECT_ID(N'dbo.audit_log', N'U') IS NOT NULL ALTER TABLE dbo.[audit_log] NOCHECK CONSTRAINT ALL;
IF OBJECT_ID(N'dbo.donations', N'U') IS NOT NULL ALTER TABLE dbo.[donations] NOCHECK CONSTRAINT ALL;
IF OBJECT_ID(N'dbo.in_kind_donation_items', N'U') IS NOT NULL ALTER TABLE dbo.[in_kind_donation_items] NOCHECK CONSTRAINT ALL;
IF OBJECT_ID(N'dbo.donation_allocations', N'U') IS NOT NULL ALTER TABLE dbo.[donation_allocations] NOCHECK CONSTRAINT ALL;
IF OBJECT_ID(N'dbo.process_recordings', N'U') IS NOT NULL ALTER TABLE dbo.[process_recordings] NOCHECK CONSTRAINT ALL;
IF OBJECT_ID(N'dbo.home_visitations', N'U') IS NOT NULL ALTER TABLE dbo.[home_visitations] NOCHECK CONSTRAINT ALL;
IF OBJECT_ID(N'dbo.education_records', N'U') IS NOT NULL ALTER TABLE dbo.[education_records] NOCHECK CONSTRAINT ALL;
IF OBJECT_ID(N'dbo.health_wellbeing_records', N'U') IS NOT NULL ALTER TABLE dbo.[health_wellbeing_records] NOCHECK CONSTRAINT ALL;
IF OBJECT_ID(N'dbo.intervention_plans', N'U') IS NOT NULL ALTER TABLE dbo.[intervention_plans] NOCHECK CONSTRAINT ALL;
IF OBJECT_ID(N'dbo.incident_reports', N'U') IS NOT NULL ALTER TABLE dbo.[incident_reports] NOCHECK CONSTRAINT ALL;
IF OBJECT_ID(N'dbo.safehouse_monthly_metrics', N'U') IS NOT NULL ALTER TABLE dbo.[safehouse_monthly_metrics] NOCHECK CONSTRAINT ALL;
IF OBJECT_ID(N'dbo.public_impact_snapshots', N'U') IS NOT NULL ALTER TABLE dbo.[public_impact_snapshots] NOCHECK CONSTRAINT ALL;
IF OBJECT_ID(N'dbo.public_impact_snapshots', N'U') IS NOT NULL DELETE FROM dbo.[public_impact_snapshots];
IF OBJECT_ID(N'dbo.safehouse_monthly_metrics', N'U') IS NOT NULL DELETE FROM dbo.[safehouse_monthly_metrics];
IF OBJECT_ID(N'dbo.incident_reports', N'U') IS NOT NULL DELETE FROM dbo.[incident_reports];
IF OBJECT_ID(N'dbo.intervention_plans', N'U') IS NOT NULL DELETE FROM dbo.[intervention_plans];
IF OBJECT_ID(N'dbo.health_wellbeing_records', N'U') IS NOT NULL DELETE FROM dbo.[health_wellbeing_records];
IF OBJECT_ID(N'dbo.education_records', N'U') IS NOT NULL DELETE FROM dbo.[education_records];
IF OBJECT_ID(N'dbo.home_visitations', N'U') IS NOT NULL DELETE FROM dbo.[home_visitations];
IF OBJECT_ID(N'dbo.process_recordings', N'U') IS NOT NULL DELETE FROM dbo.[process_recordings];
IF OBJECT_ID(N'dbo.donation_allocations', N'U') IS NOT NULL DELETE FROM dbo.[donation_allocations];
IF OBJECT_ID(N'dbo.in_kind_donation_items', N'U') IS NOT NULL DELETE FROM dbo.[in_kind_donation_items];
IF OBJECT_ID(N'dbo.donations', N'U') IS NOT NULL DELETE FROM dbo.[donations];
IF OBJECT_ID(N'dbo.audit_log', N'U') IS NOT NULL DELETE FROM dbo.[audit_log];
IF OBJECT_ID(N'dbo.users', N'U') IS NOT NULL DELETE FROM dbo.[users];
IF OBJECT_ID(N'dbo.residents', N'U') IS NOT NULL DELETE FROM dbo.[residents];
IF OBJECT_ID(N'dbo.partner_assignments', N'U') IS NOT NULL DELETE FROM dbo.[partner_assignments];
IF OBJECT_ID(N'dbo.social_media_posts', N'U') IS NOT NULL DELETE FROM dbo.[social_media_posts];
IF OBJECT_ID(N'dbo.supporters', N'U') IS NOT NULL DELETE FROM dbo.[supporters];
IF OBJECT_ID(N'dbo.partners', N'U') IS NOT NULL DELETE FROM dbo.[partners];
IF OBJECT_ID(N'dbo.staff', N'U') IS NOT NULL DELETE FROM dbo.[staff];
IF OBJECT_ID(N'dbo.safehouses', N'U') IS NOT NULL DELETE FROM dbo.[safehouses];
IF OBJECT_ID(N'dbo.roles_permissions', N'U') IS NOT NULL DELETE FROM dbo.[roles_permissions];
IF OBJECT_ID(N'dbo.program_areas', N'U') IS NOT NULL DELETE FROM dbo.[program_areas];
IF OBJECT_ID(N'dbo.organization', N'U') IS NOT NULL DELETE FROM dbo.[organization];

-- organization
IF OBJECT_ID(N'dbo.organization', N'U') IS NOT NULL
BEGIN
  IF EXISTS (SELECT 1 FROM sys.identity_columns WHERE object_id = OBJECT_ID(N'dbo.organization')) EXEC('SET IDENTITY_INSERT dbo.organization ON');
  INSERT INTO dbo.[organization] ([org_id], [org_name], [legal_name], [org_type], [ein], [country_of_registration], [operations_country], [address_line1], [address_line2], [city], [state], [zip_code], [country], [phone], [email], [website], [logo_url], [mission_statement], [founded_year], [fiscal_year_start], [fiscal_year_end], [currency_primary], [currency_reporting], [created_at], [updated_at]) VALUES
(1, N'Lighthouse Sanctuary', N'Lighthouse Sanctuary Inc.', N'501(c)(3) Nonprofit', N'XX-XXXXXXX', N'United States', N'Philippines', NULL, NULL, NULL, NULL, NULL, N'United States', NULL, N'info@lighthouseph.org', N'https://lighthouse.ph', NULL, N'To provide safe homes and rehabilitation services for girls who are survivors of sexual abuse and sex trafficking in the Philippines.', 2022, N'01-01', N'12-31', N'PHP', N'USD', N'2022-01-01 00:00:00', N'2026-04-06 00:00:00');
  IF EXISTS (SELECT 1 FROM sys.identity_columns WHERE object_id = OBJECT_ID(N'dbo.organization')) EXEC('SET IDENTITY_INSERT dbo.organization OFF');
END

-- program_areas
IF OBJECT_ID(N'dbo.program_areas', N'U') IS NOT NULL
BEGIN
  IF EXISTS (SELECT 1 FROM sys.identity_columns WHERE object_id = OBJECT_ID(N'dbo.program_areas')) EXEC('SET IDENTITY_INSERT dbo.program_areas ON');
  INSERT INTO dbo.[program_areas] ([program_area_id], [area_code], [area_name], [description], [applies_to], [is_active]) VALUES
(1, N'EDU', N'Education', N'Covers schooling, vocational training, enrollment support, and academic progress tracking for residents.', N'donations, intervention_plans', 1),
(2, N'OPS', N'Operations', N'General safehouse operations including staffing, utilities, and day-to-day management.', N'donations, partner_assignments', 1),
(3, N'OUT', N'Outreach', N'Community outreach, awareness campaigns, and external engagement activities.', N'donations, partner_assignments', 1),
(4, N'PHY', N'Physical Health', N'Medical checkups, dental care, nutrition, and physical wellbeing services for residents.', N'donations, intervention_plans', 1),
(5, N'SAF', N'Safety', N'Safety planning, risk assessment, and protective measures for residents.', N'donations, intervention_plans', 1),
(6, N'TRN', N'Transport', N'Transportation costs for residents, home visitations, court appearances, and medical appointments.', N'donations', 1),
(7, N'WEL', N'Wellbeing', N'Psychological counseling, therapeutic sessions, and emotional support services.', N'donations, intervention_plans', 1),
(8, N'MNT', N'Maintenance', N'Safehouse facility maintenance, repairs, and upkeep.', N'donations, partner_assignments', 1);
  IF EXISTS (SELECT 1 FROM sys.identity_columns WHERE object_id = OBJECT_ID(N'dbo.program_areas')) EXEC('SET IDENTITY_INSERT dbo.program_areas OFF');
END

-- roles_permissions
IF OBJECT_ID(N'dbo.roles_permissions', N'U') IS NOT NULL
BEGIN
  IF EXISTS (SELECT 1 FROM sys.identity_columns WHERE object_id = OBJECT_ID(N'dbo.roles_permissions')) EXEC('SET IDENTITY_INSERT dbo.roles_permissions ON');
  INSERT INTO dbo.[roles_permissions] ([permission_id], [role], [resource], [action], [is_allowed], [scope_note]) VALUES
(1, N'Admin', N'residents', N'view', 1, NULL),
(2, N'Admin', N'residents', N'create', 1, NULL),
(3, N'Admin', N'residents', N'edit', 1, NULL),
(4, N'Admin', N'residents', N'delete', 1, NULL),
(5, N'Admin', N'health_records', N'view', 1, NULL),
(6, N'Admin', N'health_records', N'create', 1, NULL),
(7, N'Admin', N'health_records', N'edit', 1, NULL),
(8, N'Admin', N'health_records', N'delete', 1, NULL),
(9, N'Admin', N'education_records', N'view', 1, NULL),
(10, N'Admin', N'education_records', N'create', 1, NULL),
(11, N'Admin', N'education_records', N'edit', 1, NULL),
(12, N'Admin', N'education_records', N'delete', 1, NULL),
(13, N'Admin', N'process_recordings', N'view', 1, NULL),
(14, N'Admin', N'process_recordings', N'create', 1, NULL),
(15, N'Admin', N'process_recordings', N'edit', 1, NULL),
(16, N'Admin', N'process_recordings', N'delete', 1, NULL),
(17, N'Admin', N'home_visitations', N'view', 1, NULL),
(18, N'Admin', N'home_visitations', N'create', 1, NULL),
(19, N'Admin', N'home_visitations', N'edit', 1, NULL),
(20, N'Admin', N'home_visitations', N'delete', 1, NULL),
(21, N'Admin', N'incident_reports', N'view', 1, NULL),
(22, N'Admin', N'incident_reports', N'create', 1, NULL),
(23, N'Admin', N'incident_reports', N'edit', 1, NULL),
(24, N'Admin', N'incident_reports', N'delete', 1, NULL),
(25, N'Admin', N'intervention_plans', N'view', 1, NULL),
(26, N'Admin', N'intervention_plans', N'create', 1, NULL),
(27, N'Admin', N'intervention_plans', N'edit', 1, NULL),
(28, N'Admin', N'intervention_plans', N'delete', 1, NULL),
(29, N'Admin', N'donations', N'view', 1, NULL),
(30, N'Admin', N'donations', N'create', 1, NULL),
(31, N'Admin', N'donations', N'edit', 1, NULL),
(32, N'Admin', N'donations', N'delete', 1, NULL),
(33, N'Admin', N'users', N'view', 1, NULL),
(34, N'Admin', N'users', N'create', 1, NULL),
(35, N'Admin', N'users', N'edit', 1, NULL),
(36, N'Admin', N'users', N'delete', 1, NULL),
(37, N'Admin', N'staff', N'view', 1, NULL),
(38, N'Admin', N'staff', N'create', 1, NULL),
(39, N'Admin', N'staff', N'edit', 1, NULL),
(40, N'Admin', N'staff', N'delete', 1, NULL),
(41, N'Admin', N'safehouses', N'view', 1, NULL),
(42, N'Admin', N'safehouses', N'create', 1, NULL),
(43, N'Admin', N'safehouses', N'edit', 1, NULL),
(44, N'Admin', N'safehouses', N'delete', 1, NULL),
(45, N'Admin', N'reports', N'view', 1, NULL),
(46, N'Admin', N'reports', N'create', 1, NULL),
(47, N'Admin', N'reports', N'edit', 1, NULL),
(48, N'Admin', N'reports', N'delete', 1, NULL),
(49, N'Admin', N'audit_log', N'view', 1, NULL),
(50, N'Admin', N'audit_log', N'create', 0, NULL),
(51, N'Admin', N'audit_log', N'edit', 0, NULL),
(52, N'Admin', N'audit_log', N'delete', 0, NULL),
(53, N'Admin', N'organization', N'view', 1, NULL),
(54, N'Admin', N'organization', N'create', 1, NULL),
(55, N'Admin', N'organization', N'edit', 1, NULL),
(56, N'Admin', N'organization', N'delete', 1, NULL),
(57, N'Supervisor', N'residents', N'view', 1, NULL),
(58, N'Supervisor', N'residents', N'create', 1, NULL),
(59, N'Supervisor', N'residents', N'edit', 1, NULL),
(60, N'Supervisor', N'residents', N'delete', 0, NULL),
(61, N'Supervisor', N'health_records', N'view', 1, NULL),
(62, N'Supervisor', N'health_records', N'create', 1, NULL),
(63, N'Supervisor', N'health_records', N'edit', 1, NULL),
(64, N'Supervisor', N'health_records', N'delete', 0, NULL),
(65, N'Supervisor', N'education_records', N'view', 1, NULL),
(66, N'Supervisor', N'education_records', N'create', 1, NULL),
(67, N'Supervisor', N'education_records', N'edit', 1, NULL),
(68, N'Supervisor', N'education_records', N'delete', 0, NULL),
(69, N'Supervisor', N'process_recordings', N'view', 1, NULL),
(70, N'Supervisor', N'process_recordings', N'create', 1, NULL),
(71, N'Supervisor', N'process_recordings', N'edit', 1, NULL),
(72, N'Supervisor', N'process_recordings', N'delete', 0, NULL),
(73, N'Supervisor', N'home_visitations', N'view', 1, NULL),
(74, N'Supervisor', N'home_visitations', N'create', 1, NULL),
(75, N'Supervisor', N'home_visitations', N'edit', 1, NULL),
(76, N'Supervisor', N'home_visitations', N'delete', 0, NULL),
(77, N'Supervisor', N'incident_reports', N'view', 1, NULL),
(78, N'Supervisor', N'incident_reports', N'create', 1, NULL),
(79, N'Supervisor', N'incident_reports', N'edit', 1, NULL),
(80, N'Supervisor', N'incident_reports', N'delete', 0, NULL),
(81, N'Supervisor', N'intervention_plans', N'view', 1, NULL),
(82, N'Supervisor', N'intervention_plans', N'create', 1, NULL),
(83, N'Supervisor', N'intervention_plans', N'edit', 1, NULL),
(84, N'Supervisor', N'intervention_plans', N'delete', 0, NULL),
(85, N'Supervisor', N'donations', N'view', 1, NULL),
(86, N'Supervisor', N'donations', N'create', 0, NULL),
(87, N'Supervisor', N'donations', N'edit', 0, NULL),
(88, N'Supervisor', N'donations', N'delete', 0, NULL),
(89, N'Supervisor', N'users', N'view', 1, NULL),
(90, N'Supervisor', N'users', N'create', 1, NULL),
(91, N'Supervisor', N'users', N'edit', 1, NULL),
(92, N'Supervisor', N'users', N'delete', 0, NULL),
(93, N'Supervisor', N'staff', N'view', 1, NULL),
(94, N'Supervisor', N'staff', N'create', 0, NULL),
(95, N'Supervisor', N'staff', N'edit', 1, NULL),
(96, N'Supervisor', N'staff', N'delete', 0, NULL),
(97, N'Supervisor', N'safehouses', N'view', 1, NULL),
(98, N'Supervisor', N'safehouses', N'create', 0, NULL),
(99, N'Supervisor', N'safehouses', N'edit', 1, NULL),
(100, N'Supervisor', N'safehouses', N'delete', 0, NULL),
(101, N'Supervisor', N'reports', N'view', 1, NULL),
(102, N'Supervisor', N'reports', N'create', 1, NULL),
(103, N'Supervisor', N'reports', N'edit', 0, NULL),
(104, N'Supervisor', N'reports', N'delete', 0, NULL),
(105, N'Supervisor', N'audit_log', N'view', 1, NULL),
(106, N'Supervisor', N'audit_log', N'create', 0, NULL),
(107, N'Supervisor', N'audit_log', N'edit', 0, NULL),
(108, N'Supervisor', N'audit_log', N'delete', 0, NULL),
(109, N'Supervisor', N'organization', N'view', 1, NULL),
(110, N'Supervisor', N'organization', N'create', 0, NULL),
(111, N'Supervisor', N'organization', N'edit', 0, NULL),
(112, N'Supervisor', N'organization', N'delete', 0, NULL),
(113, N'Case Manager', N'residents', N'view', 1, N'assigned safehouse only'),
(114, N'Case Manager', N'residents', N'create', 1, N'assigned safehouse only'),
(115, N'Case Manager', N'residents', N'edit', 1, N'assigned safehouse only'),
(116, N'Case Manager', N'residents', N'delete', 0, NULL),
(117, N'Case Manager', N'health_records', N'view', 1, NULL),
(118, N'Case Manager', N'health_records', N'create', 1, NULL),
(119, N'Case Manager', N'health_records', N'edit', 1, NULL),
(120, N'Case Manager', N'health_records', N'delete', 0, NULL),
(121, N'Case Manager', N'education_records', N'view', 1, NULL),
(122, N'Case Manager', N'education_records', N'create', 1, NULL),
(123, N'Case Manager', N'education_records', N'edit', 1, NULL),
(124, N'Case Manager', N'education_records', N'delete', 0, NULL),
(125, N'Case Manager', N'process_recordings', N'view', 1, NULL),
(126, N'Case Manager', N'process_recordings', N'create', 1, NULL),
(127, N'Case Manager', N'process_recordings', N'edit', 1, NULL),
(128, N'Case Manager', N'process_recordings', N'delete', 0, NULL),
(129, N'Case Manager', N'home_visitations', N'view', 1, NULL),
(130, N'Case Manager', N'home_visitations', N'create', 1, NULL),
(131, N'Case Manager', N'home_visitations', N'edit', 1, NULL),
(132, N'Case Manager', N'home_visitations', N'delete', 0, NULL),
(133, N'Case Manager', N'incident_reports', N'view', 1, NULL),
(134, N'Case Manager', N'incident_reports', N'create', 1, NULL),
(135, N'Case Manager', N'incident_reports', N'edit', 1, NULL),
(136, N'Case Manager', N'incident_reports', N'delete', 0, NULL),
(137, N'Case Manager', N'intervention_plans', N'view', 1, NULL),
(138, N'Case Manager', N'intervention_plans', N'create', 1, NULL),
(139, N'Case Manager', N'intervention_plans', N'edit', 1, NULL),
(140, N'Case Manager', N'intervention_plans', N'delete', 0, NULL),
(141, N'Case Manager', N'donations', N'view', 0, NULL),
(142, N'Case Manager', N'donations', N'create', 0, NULL),
(143, N'Case Manager', N'donations', N'edit', 0, NULL),
(144, N'Case Manager', N'donations', N'delete', 0, NULL),
(145, N'Case Manager', N'users', N'view', 0, NULL),
(146, N'Case Manager', N'users', N'create', 0, NULL),
(147, N'Case Manager', N'users', N'edit', 0, NULL),
(148, N'Case Manager', N'users', N'delete', 0, NULL),
(149, N'Case Manager', N'staff', N'view', 1, NULL),
(150, N'Case Manager', N'staff', N'create', 0, NULL),
(151, N'Case Manager', N'staff', N'edit', 0, NULL),
(152, N'Case Manager', N'staff', N'delete', 0, NULL),
(153, N'Case Manager', N'safehouses', N'view', 1, NULL),
(154, N'Case Manager', N'safehouses', N'create', 0, NULL),
(155, N'Case Manager', N'safehouses', N'edit', 0, NULL),
(156, N'Case Manager', N'safehouses', N'delete', 0, NULL),
(157, N'Case Manager', N'reports', N'view', 1, NULL),
(158, N'Case Manager', N'reports', N'create', 1, NULL),
(159, N'Case Manager', N'reports', N'edit', 0, NULL),
(160, N'Case Manager', N'reports', N'delete', 0, NULL),
(161, N'Case Manager', N'audit_log', N'view', 0, NULL),
(162, N'Case Manager', N'audit_log', N'create', 0, NULL),
(163, N'Case Manager', N'audit_log', N'edit', 0, NULL),
(164, N'Case Manager', N'audit_log', N'delete', 0, NULL),
(165, N'Case Manager', N'organization', N'view', 1, NULL),
(166, N'Case Manager', N'organization', N'create', 0, NULL),
(167, N'Case Manager', N'organization', N'edit', 0, NULL),
(168, N'Case Manager', N'organization', N'delete', 0, NULL),
(169, N'Social Worker', N'residents', N'view', 1, N'assigned safehouse only'),
(170, N'Social Worker', N'residents', N'create', 0, NULL),
(171, N'Social Worker', N'residents', N'edit', 1, N'assigned safehouse only'),
(172, N'Social Worker', N'residents', N'delete', 0, NULL),
(173, N'Social Worker', N'health_records', N'view', 1, NULL),
(174, N'Social Worker', N'health_records', N'create', 1, NULL),
(175, N'Social Worker', N'health_records', N'edit', 1, NULL),
(176, N'Social Worker', N'health_records', N'delete', 0, NULL),
(177, N'Social Worker', N'education_records', N'view', 1, NULL),
(178, N'Social Worker', N'education_records', N'create', 1, NULL),
(179, N'Social Worker', N'education_records', N'edit', 1, NULL),
(180, N'Social Worker', N'education_records', N'delete', 0, NULL),
(181, N'Social Worker', N'process_recordings', N'view', 1, NULL),
(182, N'Social Worker', N'process_recordings', N'create', 1, NULL),
(183, N'Social Worker', N'process_recordings', N'edit', 1, NULL),
(184, N'Social Worker', N'process_recordings', N'delete', 0, NULL),
(185, N'Social Worker', N'home_visitations', N'view', 1, NULL),
(186, N'Social Worker', N'home_visitations', N'create', 1, NULL),
(187, N'Social Worker', N'home_visitations', N'edit', 1, NULL),
(188, N'Social Worker', N'home_visitations', N'delete', 0, NULL),
(189, N'Social Worker', N'incident_reports', N'view', 1, NULL),
(190, N'Social Worker', N'incident_reports', N'create', 1, NULL),
(191, N'Social Worker', N'incident_reports', N'edit', 1, NULL),
(192, N'Social Worker', N'incident_reports', N'delete', 0, NULL),
(193, N'Social Worker', N'intervention_plans', N'view', 1, NULL),
(194, N'Social Worker', N'intervention_plans', N'create', 0, NULL),
(195, N'Social Worker', N'intervention_plans', N'edit', 1, NULL),
(196, N'Social Worker', N'intervention_plans', N'delete', 0, NULL),
(197, N'Social Worker', N'donations', N'view', 0, NULL),
(198, N'Social Worker', N'donations', N'create', 0, NULL),
(199, N'Social Worker', N'donations', N'edit', 0, NULL),
(200, N'Social Worker', N'donations', N'delete', 0, NULL),
(201, N'Social Worker', N'users', N'view', 0, NULL),
(202, N'Social Worker', N'users', N'create', 0, NULL),
(203, N'Social Worker', N'users', N'edit', 0, NULL),
(204, N'Social Worker', N'users', N'delete', 0, NULL),
(205, N'Social Worker', N'staff', N'view', 1, NULL),
(206, N'Social Worker', N'staff', N'create', 0, NULL),
(207, N'Social Worker', N'staff', N'edit', 0, NULL),
(208, N'Social Worker', N'staff', N'delete', 0, NULL),
(209, N'Social Worker', N'safehouses', N'view', 1, NULL),
(210, N'Social Worker', N'safehouses', N'create', 0, NULL),
(211, N'Social Worker', N'safehouses', N'edit', 0, NULL),
(212, N'Social Worker', N'safehouses', N'delete', 0, NULL),
(213, N'Social Worker', N'reports', N'view', 1, NULL),
(214, N'Social Worker', N'reports', N'create', 0, NULL),
(215, N'Social Worker', N'reports', N'edit', 0, NULL),
(216, N'Social Worker', N'reports', N'delete', 0, NULL),
(217, N'Social Worker', N'audit_log', N'view', 0, NULL),
(218, N'Social Worker', N'audit_log', N'create', 0, NULL),
(219, N'Social Worker', N'audit_log', N'edit', 0, NULL),
(220, N'Social Worker', N'audit_log', N'delete', 0, NULL),
(221, N'Social Worker', N'organization', N'view', 1, NULL),
(222, N'Social Worker', N'organization', N'create', 0, NULL),
(223, N'Social Worker', N'organization', N'edit', 0, NULL),
(224, N'Social Worker', N'organization', N'delete', 0, NULL),
(225, N'Field Worker', N'residents', N'view', 1, N'assigned safehouse only'),
(226, N'Field Worker', N'residents', N'create', 0, NULL),
(227, N'Field Worker', N'residents', N'edit', 0, NULL),
(228, N'Field Worker', N'residents', N'delete', 0, NULL),
(229, N'Field Worker', N'health_records', N'view', 1, NULL),
(230, N'Field Worker', N'health_records', N'create', 1, NULL),
(231, N'Field Worker', N'health_records', N'edit', 0, NULL),
(232, N'Field Worker', N'health_records', N'delete', 0, NULL),
(233, N'Field Worker', N'education_records', N'view', 1, NULL),
(234, N'Field Worker', N'education_records', N'create', 1, NULL),
(235, N'Field Worker', N'education_records', N'edit', 0, NULL),
(236, N'Field Worker', N'education_records', N'delete', 0, NULL),
(237, N'Field Worker', N'process_recordings', N'view', 1, NULL),
(238, N'Field Worker', N'process_recordings', N'create', 1, NULL),
(239, N'Field Worker', N'process_recordings', N'edit', 0, NULL),
(240, N'Field Worker', N'process_recordings', N'delete', 0, NULL),
(241, N'Field Worker', N'home_visitations', N'view', 1, NULL),
(242, N'Field Worker', N'home_visitations', N'create', 1, NULL),
(243, N'Field Worker', N'home_visitations', N'edit', 0, NULL),
(244, N'Field Worker', N'home_visitations', N'delete', 0, NULL),
(245, N'Field Worker', N'incident_reports', N'view', 1, NULL),
(246, N'Field Worker', N'incident_reports', N'create', 1, NULL),
(247, N'Field Worker', N'incident_reports', N'edit', 0, NULL),
(248, N'Field Worker', N'incident_reports', N'delete', 0, NULL),
(249, N'Field Worker', N'intervention_plans', N'view', 1, NULL),
(250, N'Field Worker', N'intervention_plans', N'create', 0, NULL),
(251, N'Field Worker', N'intervention_plans', N'edit', 0, NULL),
(252, N'Field Worker', N'intervention_plans', N'delete', 0, NULL),
(253, N'Field Worker', N'donations', N'view', 0, NULL),
(254, N'Field Worker', N'donations', N'create', 0, NULL),
(255, N'Field Worker', N'donations', N'edit', 0, NULL),
(256, N'Field Worker', N'donations', N'delete', 0, NULL),
(257, N'Field Worker', N'users', N'view', 0, NULL),
(258, N'Field Worker', N'users', N'create', 0, NULL),
(259, N'Field Worker', N'users', N'edit', 0, NULL),
(260, N'Field Worker', N'users', N'delete', 0, NULL),
(261, N'Field Worker', N'staff', N'view', 0, NULL),
(262, N'Field Worker', N'staff', N'create', 0, NULL),
(263, N'Field Worker', N'staff', N'edit', 0, NULL),
(264, N'Field Worker', N'staff', N'delete', 0, NULL),
(265, N'Field Worker', N'safehouses', N'view', 1, NULL),
(266, N'Field Worker', N'safehouses', N'create', 0, NULL),
(267, N'Field Worker', N'safehouses', N'edit', 0, NULL),
(268, N'Field Worker', N'safehouses', N'delete', 0, NULL),
(269, N'Field Worker', N'reports', N'view', 0, NULL),
(270, N'Field Worker', N'reports', N'create', 0, NULL),
(271, N'Field Worker', N'reports', N'edit', 0, NULL),
(272, N'Field Worker', N'reports', N'delete', 0, NULL),
(273, N'Field Worker', N'audit_log', N'view', 0, NULL),
(274, N'Field Worker', N'audit_log', N'create', 0, NULL),
(275, N'Field Worker', N'audit_log', N'edit', 0, NULL),
(276, N'Field Worker', N'audit_log', N'delete', 0, NULL),
(277, N'Field Worker', N'organization', N'view', 1, NULL),
(278, N'Field Worker', N'organization', N'create', 0, NULL),
(279, N'Field Worker', N'organization', N'edit', 0, NULL),
(280, N'Field Worker', N'organization', N'delete', 0, NULL),
(281, N'Resident', N'residents', N'view', 1, N'own only'),
(282, N'Resident', N'residents', N'create', 0, NULL),
(283, N'Resident', N'residents', N'edit', 0, NULL),
(284, N'Resident', N'residents', N'delete', 0, NULL),
(285, N'Resident', N'health_records', N'view', 1, N'own only'),
(286, N'Resident', N'health_records', N'create', 0, NULL),
(287, N'Resident', N'health_records', N'edit', 0, NULL),
(288, N'Resident', N'health_records', N'delete', 0, NULL),
(289, N'Resident', N'education_records', N'view', 1, N'own only'),
(290, N'Resident', N'education_records', N'create', 0, NULL),
(291, N'Resident', N'education_records', N'edit', 0, NULL),
(292, N'Resident', N'education_records', N'delete', 0, NULL),
(293, N'Resident', N'process_recordings', N'view', 0, NULL),
(294, N'Resident', N'process_recordings', N'create', 0, NULL),
(295, N'Resident', N'process_recordings', N'edit', 0, NULL),
(296, N'Resident', N'process_recordings', N'delete', 0, NULL),
(297, N'Resident', N'home_visitations', N'view', 1, N'own only'),
(298, N'Resident', N'home_visitations', N'create', 0, NULL),
(299, N'Resident', N'home_visitations', N'edit', 0, NULL),
(300, N'Resident', N'home_visitations', N'delete', 0, NULL),
(301, N'Resident', N'incident_reports', N'view', 0, NULL),
(302, N'Resident', N'incident_reports', N'create', 0, NULL),
(303, N'Resident', N'incident_reports', N'edit', 0, NULL),
(304, N'Resident', N'incident_reports', N'delete', 0, NULL),
(305, N'Resident', N'intervention_plans', N'view', 1, N'own only'),
(306, N'Resident', N'intervention_plans', N'create', 0, NULL),
(307, N'Resident', N'intervention_plans', N'edit', 0, NULL),
(308, N'Resident', N'intervention_plans', N'delete', 0, NULL),
(309, N'Resident', N'donations', N'view', 0, NULL),
(310, N'Resident', N'donations', N'create', 0, NULL),
(311, N'Resident', N'donations', N'edit', 0, NULL),
(312, N'Resident', N'donations', N'delete', 0, NULL),
(313, N'Resident', N'users', N'view', 0, NULL),
(314, N'Resident', N'users', N'create', 0, NULL),
(315, N'Resident', N'users', N'edit', 0, NULL),
(316, N'Resident', N'users', N'delete', 0, NULL),
(317, N'Resident', N'staff', N'view', 0, NULL),
(318, N'Resident', N'staff', N'create', 0, NULL),
(319, N'Resident', N'staff', N'edit', 0, NULL),
(320, N'Resident', N'staff', N'delete', 0, NULL),
(321, N'Resident', N'safehouses', N'view', 0, NULL),
(322, N'Resident', N'safehouses', N'create', 0, NULL),
(323, N'Resident', N'safehouses', N'edit', 0, NULL),
(324, N'Resident', N'safehouses', N'delete', 0, NULL),
(325, N'Resident', N'reports', N'view', 0, NULL),
(326, N'Resident', N'reports', N'create', 0, NULL),
(327, N'Resident', N'reports', N'edit', 0, NULL),
(328, N'Resident', N'reports', N'delete', 0, NULL),
(329, N'Resident', N'audit_log', N'view', 0, NULL),
(330, N'Resident', N'audit_log', N'create', 0, NULL),
(331, N'Resident', N'audit_log', N'edit', 0, NULL),
(332, N'Resident', N'audit_log', N'delete', 0, NULL),
(333, N'Resident', N'organization', N'view', 1, NULL),
(334, N'Resident', N'organization', N'create', 0, NULL),
(335, N'Resident', N'organization', N'edit', 0, NULL),
(336, N'Resident', N'organization', N'delete', 0, NULL),
(337, N'Donor', N'residents', N'view', 0, NULL),
(338, N'Donor', N'residents', N'create', 0, NULL),
(339, N'Donor', N'residents', N'edit', 0, NULL),
(340, N'Donor', N'residents', N'delete', 0, NULL),
(341, N'Donor', N'health_records', N'view', 0, NULL),
(342, N'Donor', N'health_records', N'create', 0, NULL),
(343, N'Donor', N'health_records', N'edit', 0, NULL),
(344, N'Donor', N'health_records', N'delete', 0, NULL),
(345, N'Donor', N'education_records', N'view', 0, NULL),
(346, N'Donor', N'education_records', N'create', 0, NULL),
(347, N'Donor', N'education_records', N'edit', 0, NULL),
(348, N'Donor', N'education_records', N'delete', 0, NULL),
(349, N'Donor', N'process_recordings', N'view', 0, NULL),
(350, N'Donor', N'process_recordings', N'create', 0, NULL),
(351, N'Donor', N'process_recordings', N'edit', 0, NULL),
(352, N'Donor', N'process_recordings', N'delete', 0, NULL),
(353, N'Donor', N'home_visitations', N'view', 0, NULL),
(354, N'Donor', N'home_visitations', N'create', 0, NULL),
(355, N'Donor', N'home_visitations', N'edit', 0, NULL),
(356, N'Donor', N'home_visitations', N'delete', 0, NULL),
(357, N'Donor', N'incident_reports', N'view', 0, NULL),
(358, N'Donor', N'incident_reports', N'create', 0, NULL),
(359, N'Donor', N'incident_reports', N'edit', 0, NULL),
(360, N'Donor', N'incident_reports', N'delete', 0, NULL),
(361, N'Donor', N'intervention_plans', N'view', 0, NULL),
(362, N'Donor', N'intervention_plans', N'create', 0, NULL),
(363, N'Donor', N'intervention_plans', N'edit', 0, NULL),
(364, N'Donor', N'intervention_plans', N'delete', 0, NULL),
(365, N'Donor', N'donations', N'view', 1, N'own only'),
(366, N'Donor', N'donations', N'create', 1, N'own only'),
(367, N'Donor', N'donations', N'edit', 0, NULL),
(368, N'Donor', N'donations', N'delete', 0, NULL),
(369, N'Donor', N'users', N'view', 0, NULL),
(370, N'Donor', N'users', N'create', 0, NULL),
(371, N'Donor', N'users', N'edit', 0, NULL),
(372, N'Donor', N'users', N'delete', 0, NULL),
(373, N'Donor', N'staff', N'view', 0, NULL),
(374, N'Donor', N'staff', N'create', 0, NULL),
(375, N'Donor', N'staff', N'edit', 0, NULL),
(376, N'Donor', N'staff', N'delete', 0, NULL),
(377, N'Donor', N'safehouses', N'view', 0, NULL),
(378, N'Donor', N'safehouses', N'create', 0, NULL),
(379, N'Donor', N'safehouses', N'edit', 0, NULL),
(380, N'Donor', N'safehouses', N'delete', 0, NULL),
(381, N'Donor', N'reports', N'view', 1, N'public only'),
(382, N'Donor', N'reports', N'create', 0, NULL),
(383, N'Donor', N'reports', N'edit', 0, NULL),
(384, N'Donor', N'reports', N'delete', 0, NULL),
(385, N'Donor', N'audit_log', N'view', 0, NULL),
(386, N'Donor', N'audit_log', N'create', 0, NULL),
(387, N'Donor', N'audit_log', N'edit', 0, NULL),
(388, N'Donor', N'audit_log', N'delete', 0, NULL),
(389, N'Donor', N'organization', N'view', 1, NULL),
(390, N'Donor', N'organization', N'create', 0, NULL),
(391, N'Donor', N'organization', N'edit', 0, NULL),
(392, N'Donor', N'organization', N'delete', 0, NULL);
  IF EXISTS (SELECT 1 FROM sys.identity_columns WHERE object_id = OBJECT_ID(N'dbo.roles_permissions')) EXEC('SET IDENTITY_INSERT dbo.roles_permissions OFF');
END

-- safehouses
IF OBJECT_ID(N'dbo.safehouses', N'U') IS NOT NULL
BEGIN
  IF EXISTS (SELECT 1 FROM sys.identity_columns WHERE object_id = OBJECT_ID(N'dbo.safehouses')) EXEC('SET IDENTITY_INSERT dbo.safehouses ON');
  INSERT INTO dbo.[safehouses] ([safehouse_id], [safehouse_code], [name], [region], [city], [province], [country], [open_date], [status], [capacity_girls], [capacity_staff], [current_occupancy], [notes]) VALUES
(1, N'SH01', N'Lighthouse Safehouse 1', N'Luzon', N'Quezon City', N'Metro Manila', N'Philippines', N'2022-01-01', N'Active', 8, 4, 8, NULL),
(2, N'SH02', N'Lighthouse Safehouse 2', N'Visayas', N'Cebu City', N'Cebu', N'Philippines', N'2022-02-15', N'Active', 10, 5, 8, NULL),
(3, N'SH03', N'Lighthouse Safehouse 3', N'Mindanao', N'Davao City', N'Davao del Sur', N'Philippines', N'2022-04-01', N'Active', 9, 4, 9, NULL),
(4, N'SH04', N'Lighthouse Safehouse 4', N'Visayas', N'Iloilo City', N'Iloilo', N'Philippines', N'2022-05-16', N'Active', 12, 4, 12, NULL),
(5, N'SH05', N'Lighthouse Safehouse 5', N'Luzon', N'Baguio City', N'Benguet', N'Philippines', N'2022-06-30', N'Active', 11, 4, 9, NULL),
(6, N'SH06', N'Lighthouse Safehouse 6', N'Mindanao', N'Cagayan de Oro', N'Misamis Oriental', N'Philippines', N'2022-08-14', N'Active', 8, 5, 6, NULL),
(7, N'SH07', N'Lighthouse Safehouse 7', N'Visayas', N'Bacolod', N'Negros Occidental', N'Philippines', N'2022-09-28', N'Active', 12, 4, 12, NULL),
(8, N'SH08', N'Lighthouse Safehouse 8', N'Visayas', N'Tacloban', N'Leyte', N'Philippines', N'2022-11-12', N'Active', 9, 7, 7, NULL),
(9, N'SH09', N'Lighthouse Safehouse 9', N'Mindanao', N'General Santos', N'South Cotabato', N'Philippines', N'2022-12-27', N'Active', 6, 3, 6, NULL),
(10, N'SH10', N'Lighthouse Safehouse 10', N'Luzon', N'Manila', N'Metro Manila', N'Philippines', N'2023-01-15', N'Active', 10, 4, 9, NULL);
  IF EXISTS (SELECT 1 FROM sys.identity_columns WHERE object_id = OBJECT_ID(N'dbo.safehouses')) EXEC('SET IDENTITY_INSERT dbo.safehouses OFF');
END

-- staff
IF OBJECT_ID(N'dbo.staff', N'U') IS NOT NULL
BEGIN
  IF EXISTS (SELECT 1 FROM sys.identity_columns WHERE object_id = OBJECT_ID(N'dbo.staff')) EXEC('SET IDENTITY_INSERT dbo.staff ON');
  INSERT INTO dbo.[staff] ([staff_id], [staff_code], [first_name], [last_name], [age], [email], [phone], [role], [employment_type], [specialization], [safehouse_id], [employment_status], [date_hired], [date_ended], [created_at], [updated_at]) VALUES
(1, N'SW-01', N'Elena', N'Santos', 31, N'elena.santos@lighthouseph.org', N'+63 941 328 3286', N'Social Worker', N'Internal', N'Trafficking', 1, N'Active', N'2023-02-22', NULL, N'2023-02-22 00:00:00', N'2026-04-06 00:00:00'),
