// <auto-generated />
using System;
using HirayaHaven.Api.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace HirayaHaven.Api.Migrations.SqlServer
{
    [DbContext(typeof(HirayaSqlServerContext))]
    [Migration("20260409201841_AddResidentAndUserNames")]
    partial class AddResidentAndUserNames
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "10.0.1")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("HirayaHaven.Api.Models.AppUser", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int>("AccessFailedCount")
                        .HasColumnType("int");

                    b.Property<DateTime?>("ApprovedAt")
                        .HasColumnType("datetime2");

                    b.Property<int?>("ApprovedBy")
                        .HasColumnType("int");

                    b.Property<string>("ConcurrencyStamp")
                        .IsConcurrencyToken()
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime2");

                    b.Property<int?>("CreatedBy")
                        .HasColumnType("int");

                    b.Property<string>("Email")
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.Property<bool>("EmailConfirmed")
                        .HasColumnType("bit");

                    b.Property<string>("FirstName")
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("first_name");

                    b.Property<bool>("IsActive")
                        .HasColumnType("bit");

                    b.Property<bool>("IsApproved")
                        .HasColumnType("bit");

                    b.Property<DateTime?>("LastLogin")
                        .HasColumnType("datetime2");

                    b.Property<string>("LastName")
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("last_name");

                    b.Property<bool>("LockoutEnabled")
                        .HasColumnType("bit");

                    b.Property<DateTimeOffset?>("LockoutEnd")
                        .HasColumnType("datetimeoffset");

                    b.Property<string>("MfaSecret")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("NormalizedEmail")
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.Property<string>("NormalizedUserName")
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.Property<string>("PasswordHash")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("PhoneNumber")
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("PhoneNumberConfirmed")
                        .HasColumnType("bit");

                    b.Property<int?>("ResetInitiatedBy")
                        .HasColumnType("int");

                    b.Property<int?>("ResidentId")
                        .HasColumnType("int");

                    b.Property<string>("SecurityStamp")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int?>("StaffId")
                        .HasColumnType("int");

                    b.Property<int?>("SupporterId")
                        .HasColumnType("int");

                    b.Property<bool>("TwoFactorEnabled")
                        .HasColumnType("bit");

                    b.Property<DateTime>("UpdatedAt")
                        .HasColumnType("datetime2");

                    b.Property<string>("UserName")
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.Property<string>("UserType")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.HasIndex("ApprovedBy");

                    b.HasIndex("CreatedBy");

                    b.HasIndex("NormalizedEmail")
                        .HasDatabaseName("EmailIndex");

                    b.HasIndex("NormalizedUserName")
                        .IsUnique()
                        .HasDatabaseName("UserNameIndex")
                        .HasFilter("[NormalizedUserName] IS NOT NULL");

                    b.HasIndex("ResetInitiatedBy");

                    b.HasIndex("ResidentId");

                    b.HasIndex("StaffId");

                    b.HasIndex("SupporterId");

                    b.ToTable("AspNetUsers", (string)null);
                });

            modelBuilder.Entity("HirayaHaven.Api.Models.AuditLog", b =>
                {
                    b.Property<int>("AuditId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("audit_id");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("AuditId"));

                    b.Property<string>("Action")
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("action");

                    b.Property<string>("ApprovalStatus")
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("approval_status");

                    b.Property<string>("ApprovedAt")
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("approved_at");

                    b.Property<int?>("ApprovedBy")
                        .HasColumnType("int")
                        .HasColumnName("approved_by");

                    b.Property<string>("IpAddress")
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("ip_address");

                    b.Property<string>("NewValue")
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("new_value");

                    b.Property<string>("Notes")
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("notes");

                    b.Property<string>("OldValue")
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("old_value");

                    b.Property<int?>("RecordId")
                        .HasColumnType("int")
                        .HasColumnName("record_id");

                    b.Property<bool?>("RequiresApproval")
                        .HasColumnType("bit")
                        .HasColumnName("requires_approval");

                    b.Property<string>("Resource")
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("resource");

                    b.Property<string>("Timestamp")
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("timestamp");

                    b.Property<int>("UserId")
                        .HasColumnType("int")
                        .HasColumnName("user_id");

                    b.HasKey("AuditId");

                    b.HasIndex("ApprovedBy");

                    b.HasIndex("UserId");

                    b.ToTable("audit_log", (string)null);
                });

            modelBuilder.Entity("HirayaHaven.Api.Models.Donation", b =>
                {
                    b.Property<int>("DonationId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("donation_id");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("DonationId"));

                    b.Property<decimal?>("Amount")
                        .HasColumnType("decimal(18,2)")
                        .HasColumnName("amount");

                    b.Property<string>("CampaignName")
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("campaign_name");

                    b.Property<string>("ChannelSource")
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("channel_source");

                    b.Property<string>("CurrencyCode")
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("currency_code");

                    b.Property<string>("DonationDate")
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("donation_date");

                    b.Property<string>("DonationType")
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("donation_type");

                    b.Property<decimal?>("EstimatedValue")
                        .HasColumnType("decimal(18,2)")
                        .HasColumnName("estimated_value");

                    b.Property<string>("ImpactUnit")
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("impact_unit");

                    b.Property<bool?>("IsRecurring")
                        .HasColumnType("bit")
                        .HasColumnName("is_recurring");

                    b.Property<string>("Notes")
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("notes");

                    b.Property<int?>("ReferralPostId")
                        .HasColumnType("int")
                        .HasColumnName("referral_post_id");

                    b.Property<int>("SupporterId")
                        .HasColumnType("int")
                        .HasColumnName("supporter_id");

                    b.HasKey("DonationId");

                    b.HasIndex("ReferralPostId");

                    b.HasIndex("SupporterId");

                    b.ToTable("donations", (string)null);
                });

            modelBuilder.Entity("HirayaHaven.Api.Models.DonationAllocation", b =>
                {
                    b.Property<int>("AllocationId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("allocation_id");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("AllocationId"));

                    b.Property<string>("AllocationDate")
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("allocation_date");

                    b.Property<string>("AllocationNotes")
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("allocation_notes");

                    b.Property<double?>("AmountAllocated")
                        .HasColumnType("float")
                        .HasColumnName("amount_allocated");

                    b.Property<int>("DonationId")
                        .HasColumnType("int")
                        .HasColumnName("donation_id");

                    b.Property<string>("ProgramArea")
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("program_area");

                    b.Property<int>("SafehouseId")
                        .HasColumnType("int")
                        .HasColumnName("safehouse_id");

                    b.HasKey("AllocationId");

                    b.HasIndex("DonationId");

                    b.HasIndex("SafehouseId");

                    b.ToTable("donation_allocations", (string)null);
                });

            modelBuilder.Entity("HirayaHaven.Api.Models.EducationRecord", b =>
                {
                    b.Property<int>("EducationRecordId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("education_record_id");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("EducationRecordId"));

                    b.Property<double?>("AttendanceRate")
                        .HasColumnType("float")
                        .HasColumnName("attendance_rate");

                    b.Property<string>("CompletionStatus")
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("completion_status");

                    b.Property<string>("EducationLevel")
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("education_level");

                    b.Property<string>("EnrollmentStatus")
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("enrollment_status");

                    b.Property<string>("Notes")
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("notes");

                    b.Property<double?>("ProgressPercent")
                        .HasColumnType("float")
                        .HasColumnName("progress_percent");

                    b.Property<string>("RecordDate")
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("record_date");

                    b.Property<int>("ResidentId")
                        .HasColumnType("int")
                        .HasColumnName("resident_id");

                    b.Property<string>("SchoolName")
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("school_name");

                    b.HasKey("EducationRecordId");

                    b.HasIndex("ResidentId");

                    b.ToTable("education_records", (string)null);
                });

            modelBuilder.Entity("HirayaHaven.Api.Models.HealthWellbeingRecord", b =>
                {
                    b.Property<int>("HealthRecordId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("health_record_id");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("HealthRecordId"));

                    b.Property<double?>("Bmi")
                        .HasColumnType("float")
                        .HasColumnName("bmi");

                    b.Property<bool?>("DentalCheckupDone")
                        .HasColumnType("bit")
                        .HasColumnName("dental_checkup_done");

                    b.Property<double?>("EnergyLevelScore")
                        .HasColumnType("float")
                        .HasColumnName("energy_level_score");

                    b.Property<double?>("GeneralHealthScore")
                        .HasColumnType("float")
                        .HasColumnName("general_health_score");

                    b.Property<double?>("HeightCm")
                        .HasColumnType("float")
                        .HasColumnName("height_cm");

                    b.Property<bool?>("MedicalCheckupDone")
                        .HasColumnType("bit")
                        .HasColumnName("medical_checkup_done");

                    b.Property<string>("Notes")
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("notes");

                    b.Property<double?>("NutritionScore")
                        .HasColumnType("float")
                        .HasColumnName("nutrition_score");

                    b.Property<bool?>("PsychologicalCheckupDone")
                        .HasColumnType("bit")
                        .HasColumnName("psychological_checkup_done");

                    b.Property<string>("RecordDate")
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("record_date");

                    b.Property<int>("ResidentId")
                        .HasColumnType("int")
                        .HasColumnName("resident_id");

                    b.Property<double?>("SleepQualityScore")
                        .HasColumnType("float")
                        .HasColumnName("sleep_quality_score");

                    b.Property<double?>("WeightKg")
                        .HasColumnType("float")
                        .HasColumnName("weight_kg");

                    b.HasKey("HealthRecordId");

                    b.HasIndex("ResidentId");

                    b.ToTable("health_wellbeing_records", (string)null);
                });

            modelBuilder.Entity("HirayaHaven.Api.Models.HomeVisitation", b =>
                {
                    b.Property<int>("VisitationId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("visitation_id");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("VisitationId"));

                    b.Property<string>("FamilyCooperationLevel")
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("family_cooperation_level");

                    b.Property<string>("FamilyMembersPresent")
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("family_members_present");

                    b.Property<bool?>("FollowUpNeeded")
                        .HasColumnType("bit")
                        .HasColumnName("follow_up_needed");

                    b.Property<string>("FollowUpNotes")
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("follow_up_notes");

                    b.Property<string>("LocationVisited")
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("location_visited");

                    b.Property<string>("Observations")
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("observations");

                    b.Property<string>("Purpose")
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("purpose");

                    b.Property<int>("ResidentId")
                        .HasColumnType("int")
                        .HasColumnName("resident_id");

                    b.Property<bool?>("SafetyConcernsNoted")
                        .HasColumnType("bit")
                        .HasColumnName("safety_concerns_noted");

                    b.Property<string>("SocialWorker")
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("social_worker");

                    b.Property<string>("VisitDate")
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("visit_date");

                    b.Property<string>("VisitOutcome")
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("visit_outcome");

                    b.Property<string>("VisitType")
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("visit_type");

                    b.HasKey("VisitationId");

                    b.HasIndex("ResidentId");

                    b.ToTable("home_visitations", (string)null);
                });

            modelBuilder.Entity("HirayaHaven.Api.Models.InKindDonationItem", b =>
                {
                    b.Property<int>("ItemId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("item_id");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("ItemId"));

                    b.Property<int>("DonationId")
                        .HasColumnType("int")
                        .HasColumnName("donation_id");

                    b.Property<double?>("EstimatedUnitValue")
                        .HasColumnType("float")
                        .HasColumnName("estimated_unit_value");

                    b.Property<string>("IntendedUse")
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("intended_use");

                    b.Property<string>("ItemCategory")
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("item_category");

                    b.Property<string>("ItemName")
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("item_name");

                    b.Property<int?>("Quantity")
                        .HasColumnType("int")
                        .HasColumnName("quantity");

                    b.Property<string>("ReceivedCondition")
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("received_condition");

                    b.Property<string>("UnitOfMeasure")
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("unit_of_measure");

                    b.HasKey("ItemId");

                    b.HasIndex("DonationId");

                    b.ToTable("in_kind_donation_items", (string)null);
                });

            modelBuilder.Entity("HirayaHaven.Api.Models.IncidentReport", b =>
                {
                    b.Property<int>("IncidentId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("incident_id");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("IncidentId"));

                    b.Property<string>("Description")
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("description");

                    b.Property<bool?>("FollowUpRequired")
                        .HasColumnType("bit")
                        .HasColumnName("follow_up_required");

                    b.Property<string>("IncidentDate")
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("incident_date");

                    b.Property<string>("IncidentType")
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("incident_type");

                    b.Property<string>("ReportedBy")
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("reported_by");

                    b.Property<int>("ResidentId")
                        .HasColumnType("int")
                        .HasColumnName("resident_id");

                    b.Property<string>("ResolutionDate")
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("resolution_date");

                    b.Property<bool?>("Resolved")
                        .HasColumnType("bit")
                        .HasColumnName("resolved");

                    b.Property<string>("ResponseTaken")
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("response_taken");

                    b.Property<int>("SafehouseId")
                        .HasColumnType("int")
                        .HasColumnName("safehouse_id");

                    b.Property<string>("Severity")
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("severity");

                    b.HasKey("IncidentId");

                    b.HasIndex("ResidentId");

                    b.HasIndex("SafehouseId");

                    b.ToTable("incident_reports", (string)null);
                });

            modelBuilder.Entity("HirayaHaven.Api.Models.InterventionPlan", b =>
                {
                    b.Property<int>("PlanId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("plan_id");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("PlanId"));

                    b.Property<string>("CaseConferenceDate")
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("case_conference_date");

                    b.Property<string>("CreatedAt")
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("created_at");

                    b.Property<string>("PlanCategory")
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("plan_category");

                    b.Property<string>("PlanDescription")
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("plan_description");

                    b.Property<int>("ResidentId")
                        .HasColumnType("int")
                        .HasColumnName("resident_id");

                    b.Property<string>("ServicesProvided")
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("services_provided");

                    b.Property<string>("Status")
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("status");

                    b.Property<string>("TargetDate")
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("target_date");

                    b.Property<double?>("TargetValue")
                        .HasColumnType("float")
                        .HasColumnName("target_value");

                    b.Property<string>("UpdatedAt")
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("updated_at");

                    b.HasKey("PlanId");

                    b.HasIndex("ResidentId");

                    b.ToTable("intervention_plans", (string)null);
                });

            modelBuilder.Entity("HirayaHaven.Api.Models.OkrTarget", b =>
                {
                    b.Property<int>("TargetId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("target_id");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("TargetId"));

                    b.Property<string>("MetricKey")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("metric_key");

                    b.Property<string>("Notes")
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("notes");

                    b.Property<int>("Quarter")
                        .HasColumnType("int")
                        .HasColumnName("quarter");

                    b.Property<double>("TargetValue")
                        .HasColumnType("float")
                        .HasColumnName("target_value");

                    b.Property<int>("Year")
                        .HasColumnType("int")
                        .HasColumnName("year");

                    b.HasKey("TargetId");

                    b.ToTable("okr_targets", (string)null);
                });

            modelBuilder.Entity("HirayaHaven.Api.Models.Organization", b =>
                {
                    b.Property<int>("OrgId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("org_id");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("OrgId"));

                    b.Property<string>("AddressLine1")
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("address_line1");

                    b.Property<string>("AddressLine2")
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("address_line2");

                    b.Property<string>("City")
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("city");

                    b.Property<string>("Country")
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("country");

                    b.Property<string>("CountryOfRegistration")
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("country_of_registration");

                    b.Property<string>("CreatedAt")
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("created_at");

                    b.Property<string>("CurrencyPrimary")
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("currency_primary");

                    b.Property<string>("CurrencyReporting")
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("currency_reporting");

                    b.Property<string>("Ein")
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("ein");

                    b.Property<string>("Email")
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("email");

                    b.Property<string>("FiscalYearEnd")
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("fiscal_year_end");

                    b.Property<string>("FiscalYearStart")
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("fiscal_year_start");

                    b.Property<int?>("FoundedYear")
                        .HasColumnType("int")
                        .HasColumnName("founded_year");

                    b.Property<string>("LegalName")
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("legal_name");

                    b.Property<string>("LogoUrl")
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("logo_url");

                    b.Property<string>("MissionStatement")
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("mission_statement");

                    b.Property<string>("OperationsCountry")
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("operations_country");

                    b.Property<string>("OrgName")
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("org_name");

                    b.Property<string>("OrgType")
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("org_type");

                    b.Property<string>("Phone")
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("phone");

                    b.Property<string>("State")
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("state");

                    b.Property<string>("UpdatedAt")
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("updated_at");

                    b.Property<string>("Website")
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("website");

                    b.Property<string>("ZipCode")
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("zip_code");

                    b.HasKey("OrgId");

                    b.ToTable("organization", (string)null);
                });

            modelBuilder.Entity("HirayaHaven.Api.Models.Partner", b =>
                {
                    b.Property<int>("PartnerId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("partner_id");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("PartnerId"));

                    b.Property<string>("ContactName")
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("contact_name");

                    b.Property<string>("Email")
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("email");

                    b.Property<string>("EndDate")
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("end_date");

                    b.Property<string>("Notes")
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("notes");

                    b.Property<string>("PartnerName")
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("partner_name");

                    b.Property<string>("PartnerType")
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("partner_type");

                    b.Property<string>("Phone")
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("phone");

                    b.Property<string>("Region")
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("region");

                    b.Property<string>("RoleType")
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("role_type");

                    b.Property<string>("StartDate")
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("start_date");

                    b.Property<string>("Status")
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("status");

                    b.HasKey("PartnerId");

                    b.ToTable("partners", (string)null);
                });

            modelBuilder.Entity("HirayaHaven.Api.Models.PartnerAssignment", b =>
                {
                    b.Property<int>("AssignmentId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("assignment_id");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("AssignmentId"));

                    b.Property<string>("AssignmentEnd")
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("assignment_end");

                    b.Property<string>("AssignmentStart")
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("assignment_start");

                    b.Property<bool?>("IsPrimary")
                        .HasColumnType("bit")
                        .HasColumnName("is_primary");

                    b.Property<int>("PartnerId")
                        .HasColumnType("int")
                        .HasColumnName("partner_id");

                    b.Property<string>("ProgramArea")
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("program_area");

                    b.Property<string>("ResponsibilityNotes")
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("responsibility_notes");

                    b.Property<int?>("SafehouseId")
                        .HasColumnType("int")
                        .HasColumnName("safehouse_id");

                    b.Property<string>("Status")
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("status");

                    b.HasKey("AssignmentId");

                    b.HasIndex("PartnerId");

                    b.HasIndex("SafehouseId");

                    b.ToTable("partner_assignments", (string)null);
                });

            modelBuilder.Entity("HirayaHaven.Api.Models.PipelineScheduleSettings", b =>
                {
                    b.Property<int>("SettingsId")
                        .HasColumnType("int")
                        .HasColumnName("settings_id");

                    b.Property<bool>("Enabled")
                        .HasColumnType("bit")
                        .HasColumnName("enabled");

                    b.Property<int>("HourUtc")
                        .HasColumnType("int")
                        .HasColumnName("hour_utc");

                    b.Property<string>("LastScheduledRunDate")
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("last_scheduled_run_date");

                    b.Property<int>("MinuteUtc")
                        .HasColumnType("int")
                        .HasColumnName("minute_utc");

                    b.HasKey("SettingsId");

                    b.ToTable("pipeline_schedule_settings", (string)null);
                });

            modelBuilder.Entity("HirayaHaven.Api.Models.PipelineTrainingRun", b =>
                {
                    b.Property<int>("RunId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("run_id");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("RunId"));

                    b.Property<string>("DetailMessage")
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("detail_message");

                    b.Property<string>("FinishedUtc")
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("finished_utc");

                    b.Property<string>("PipelineKey")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("pipeline_key");

                    b.Property<string>("StartedUtc")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("started_utc");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("status");

                    b.Property<string>("TriggerType")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("trigger_type");

                    b.Property<string>("TriggeredByUserName")
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("triggered_by_user_name");

                    b.HasKey("RunId");

                    b.ToTable("pipeline_training_runs", (string)null);
                });

            modelBuilder.Entity("HirayaHaven.Api.Models.ProcessRecording", b =>
                {
                    b.Property<int>("RecordingId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("recording_id");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("RecordingId"));

                    b.Property<bool?>("ConcernsFlagged")
                        .HasColumnType("bit")
                        .HasColumnName("concerns_flagged");

                    b.Property<string>("EmotionalStateEnd")
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("emotional_state_end");

                    b.Property<string>("EmotionalStateObserved")
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("emotional_state_observed");

                    b.Property<string>("FollowUpActions")
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("follow_up_actions");

                    b.Property<string>("InterventionsApplied")
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("interventions_applied");

                    b.Property<string>("NotesRestricted")
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("notes_restricted");

                    b.Property<bool?>("ProgressNoted")
                        .HasColumnType("bit")
                        .HasColumnName("progress_noted");

                    b.Property<bool?>("ReferralMade")
                        .HasColumnType("bit")
                        .HasColumnName("referral_made");

                    b.Property<int>("ResidentId")
                        .HasColumnType("int")
                        .HasColumnName("resident_id");

                    b.Property<string>("SessionDate")
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("session_date");

                    b.Property<int?>("SessionDurationMinutes")
                        .HasColumnType("int")
                        .HasColumnName("session_duration_minutes");

                    b.Property<string>("SessionNarrative")
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("session_narrative");

                    b.Property<string>("SessionType")
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("session_type");

                    b.Property<string>("SocialWorker")
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("social_worker");

                    b.HasKey("RecordingId");

                    b.HasIndex("ResidentId");

                    b.ToTable("process_recordings", (string)null);
                });

            modelBuilder.Entity("HirayaHaven.Api.Models.ProgramArea", b =>
                {
                    b.Property<int>("ProgramAreaId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("program_area_id");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("ProgramAreaId"));

                    b.Property<string>("AppliesTo")
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("applies_to");

                    b.Property<string>("AreaCode")
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("area_code");

                    b.Property<string>("AreaName")
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("area_name");

                    b.Property<string>("Description")
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("description");

                    b.Property<bool?>("IsActive")
                        .HasColumnType("bit")
                        .HasColumnName("is_active");

                    b.HasKey("ProgramAreaId");

                    b.ToTable("program_areas", (string)null);
                });

            modelBuilder.Entity("HirayaHaven.Api.Models.PublicImpactSnapshot", b =>
                {
                    b.Property<int>("SnapshotId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("snapshot_id");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("SnapshotId"));

                    b.Property<string>("Headline")
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("headline");

                    b.Property<bool?>("IsPublished")
                        .HasColumnType("bit")
                        .HasColumnName("is_published");

                    b.Property<string>("MetricPayloadJson")
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("metric_payload_json");

                    b.Property<string>("PublishedAt")
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("published_at");

                    b.Property<string>("SnapshotDate")
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("snapshot_date");

                    b.Property<string>("SummaryText")
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("summary_text");

                    b.HasKey("SnapshotId");

                    b.ToTable("public_impact_snapshots", (string)null);
                });

            modelBuilder.Entity("HirayaHaven.Api.Models.Resident", b =>
                {
                    b.Property<int>("ResidentId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("resident_id");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("ResidentId"));

                    b.Property<string>("AgeUponAdmission")
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("age_upon_admission");

                    b.Property<string>("AssignedSocialWorker")
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("assigned_social_worker");

                    b.Property<string>("BirthStatus")
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("birth_status");

                    b.Property<string>("CaseCategory")
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("case_category");

                    b.Property<string>("CaseControlNo")
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("case_control_no");

                    b.Property<string>("CaseStatus")
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("case_status");

                    b.Property<string>("CreatedAt")
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("created_at");

                    b.Property<string>("CurrentRiskLevel")
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("current_risk_level");

                    b.Property<string>("DateCaseStudyPrepared")
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("date_case_study_prepared");

                    b.Property<string>("DateClosed")
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("date_closed");

                    b.Property<string>("DateColbObtained")
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("date_colb_obtained");

                    b.Property<string>("DateColbRegistered")
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("date_colb_registered");

                    b.Property<string>("DateEnrolled")
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("date_enrolled");

                    b.Property<string>("DateOfAdmission")
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("date_of_admission");

                    b.Property<string>("DateOfBirth")
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("date_of_birth");

                    b.Property<bool?>("FamilyIndigenous")
                        .HasColumnType("bit")
                        .HasColumnName("family_indigenous");

                    b.Property<bool?>("FamilyInformalSettler")
                        .HasColumnType("bit")
                        .HasColumnName("family_informal_settler");

                    b.Property<bool?>("FamilyIs4ps")
                        .HasColumnType("bit")
                        .HasColumnName("family_is_4ps");

                    b.Property<bool?>("FamilyParentPwd")
                        .HasColumnType("bit")
                        .HasColumnName("family_parent_pwd");

                    b.Property<bool?>("FamilySoloParent")
                        .HasColumnType("bit")
                        .HasColumnName("family_solo_parent");

                    b.Property<bool?>("HasSpecialNeeds")
                        .HasColumnType("bit")
                        .HasColumnName("has_special_needs");

                    b.Property<string>("InitialCaseAssessment")
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("initial_case_assessment");

                    b.Property<string>("InitialRiskLevel")
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("initial_risk_level");

                    b.Property<string>("InternalCode")
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("internal_code");

                    b.Property<bool?>("IsPwd")
                        .HasColumnType("bit")
                        .HasColumnName("is_pwd");

                    b.Property<string>("LengthOfStay")
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("length_of_stay");

                    b.Property<string>("NotesRestricted")
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("notes_restricted");

                    b.Property<string>("PlaceOfBirth")
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("place_of_birth");

                    b.Property<string>("PresentAge")
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("present_age");

                    b.Property<string>("PwdType")
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("pwd_type");

                    b.Property<string>("ReferralSource")
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("referral_source");

                    b.Property<string>("ReferringAgencyPerson")
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("referring_agency_person");

                    b.Property<string>("ReintegrationStatus")
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("reintegration_status");

                    b.Property<string>("ReintegrationType")
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("reintegration_type");

                    b.Property<string>("Religion")
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("religion");

                    b.Property<string>("ResidentFirstName")
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("resident_first_name");

                    b.Property<string>("ResidentLastName")
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("resident_last_name");

                    b.Property<int?>("SafehouseId")
                        .HasColumnType("int")
                        .HasColumnName("safehouse_id");

                    b.Property<string>("Sex")
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("sex");

                    b.Property<string>("SpecialNeedsDiagnosis")
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("special_needs_diagnosis");

                    b.Property<bool?>("SubCatAtRisk")
                        .HasColumnType("bit")
                        .HasColumnName("sub_cat_at_risk");

                    b.Property<bool?>("SubCatChildLabor")
                        .HasColumnType("bit")
                        .HasColumnName("sub_cat_child_labor");

                    b.Property<bool?>("SubCatChildWithHiv")
                        .HasColumnType("bit")
                        .HasColumnName("sub_cat_child_with_hiv");

                    b.Property<bool?>("SubCatCicl")
                        .HasColumnType("bit")
                        .HasColumnName("sub_cat_cicl");

                    b.Property<bool?>("SubCatOrphaned")
                        .HasColumnType("bit")
                        .HasColumnName("sub_cat_orphaned");

                    b.Property<bool?>("SubCatOsaec")
                        .HasColumnType("bit")
                        .HasColumnName("sub_cat_osaec");

                    b.Property<bool?>("SubCatPhysicalAbuse")
                        .HasColumnType("bit")
                        .HasColumnName("sub_cat_physical_abuse");

                    b.Property<bool?>("SubCatSexualAbuse")
                        .HasColumnType("bit")
                        .HasColumnName("sub_cat_sexual_abuse");

                    b.Property<bool?>("SubCatStreetChild")
                        .HasColumnType("bit")
                        .HasColumnName("sub_cat_street_child");

                    b.Property<bool?>("SubCatTrafficked")
                        .HasColumnType("bit")
                        .HasColumnName("sub_cat_trafficked");

                    b.HasKey("ResidentId");

                    b.HasIndex("SafehouseId");

                    b.ToTable("residents", (string)null);
                });

            modelBuilder.Entity("HirayaHaven.Api.Models.RolePermission", b =>
                {
                    b.Property<int>("PermissionId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("permission_id");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("PermissionId"));

                    b.Property<string>("Action")
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("action");

                    b.Property<bool?>("IsAllowed")
                        .HasColumnType("bit")
                        .HasColumnName("is_allowed");

                    b.Property<string>("Resource")
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("resource");

                    b.Property<string>("Role")
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("role");

                    b.Property<string>("ScopeNote")
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("scope_note");

                    b.HasKey("PermissionId");

                    b.ToTable("roles_permissions", (string)null);
                });

            modelBuilder.Entity("HirayaHaven.Api.Models.Safehouse", b =>
                {
                    b.Property<int>("SafehouseId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("safehouse_id");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("SafehouseId"));

                    b.Property<int?>("CapacityGirls")
                        .HasColumnType("int")
                        .HasColumnName("capacity_girls");

                    b.Property<int?>("CapacityStaff")
                        .HasColumnType("int")
                        .HasColumnName("capacity_staff");

                    b.Property<string>("City")
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("city");

                    b.Property<string>("Country")
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("country");

                    b.Property<int?>("CurrentOccupancy")
                        .HasColumnType("int")
                        .HasColumnName("current_occupancy");

                    b.Property<string>("Name")
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("name");

                    b.Property<string>("Notes")
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("notes");

                    b.Property<string>("OpenDate")
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("open_date");

                    b.Property<string>("Province")
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("province");

                    b.Property<string>("Region")
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("region");

                    b.Property<string>("SafehouseCode")
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("safehouse_code");

                    b.Property<string>("Status")
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("status");

                    b.HasKey("SafehouseId");

                    b.ToTable("safehouses", (string)null);
                });

            modelBuilder.Entity("HirayaHaven.Api.Models.SafehouseMonthlyMetric", b =>
                {
                    b.Property<int>("MetricId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("metric_id");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("MetricId"));

                    b.Property<int?>("ActiveResidents")
                        .HasColumnType("int")
                        .HasColumnName("active_residents");

                    b.Property<double?>("AvgEducationProgress")
                        .HasColumnType("float")
                        .HasColumnName("avg_education_progress");

                    b.Property<double?>("AvgHealthScore")
                        .HasColumnType("float")
                        .HasColumnName("avg_health_score");

                    b.Property<int?>("HomeVisitationCount")
                        .HasColumnType("int")
                        .HasColumnName("home_visitation_count");

                    b.Property<int?>("IncidentCount")
                        .HasColumnType("int")
                        .HasColumnName("incident_count");

                    b.Property<string>("MonthEnd")
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("month_end");

                    b.Property<string>("MonthStart")
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("month_start");

                    b.Property<string>("Notes")
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("notes");

                    b.Property<int?>("ProcessRecordingCount")
                        .HasColumnType("int")
                        .HasColumnName("process_recording_count");

                    b.Property<int>("SafehouseId")
                        .HasColumnType("int")
                        .HasColumnName("safehouse_id");

                    b.HasKey("MetricId");

                    b.HasIndex("SafehouseId");

                    b.ToTable("safehouse_monthly_metrics", (string)null);
                });

            modelBuilder.Entity("HirayaHaven.Api.Models.SocialMediaPost", b =>
                {
                    b.Property<int>("PostId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("post_id");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("PostId"));

                    b.Property<int?>("AvgViewDurationSeconds")
                        .HasColumnType("int")
                        .HasColumnName("avg_view_duration_seconds");

                    b.Property<double?>("BoostBudgetPhp")
                        .HasColumnType("float")
                        .HasColumnName("boost_budget_php");

                    b.Property<string>("CallToActionType")
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("call_to_action_type");

                    b.Property<string>("CampaignName")
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("campaign_name");

                    b.Property<string>("Caption")
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("caption");

                    b.Property<int?>("CaptionLength")
                        .HasColumnType("int")
                        .HasColumnName("caption_length");

                    b.Property<int?>("ClickThroughs")
                        .HasColumnType("int")
                        .HasColumnName("click_throughs");

                    b.Property<int?>("Comments")
                        .HasColumnType("int")
                        .HasColumnName("comments");

                    b.Property<string>("ContentTopic")
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("content_topic");

                    b.Property<string>("CreatedAt")
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("created_at");

                    b.Property<string>("DayOfWeek")
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("day_of_week");

                    b.Property<int?>("DonationReferrals")
                        .HasColumnType("int")
                        .HasColumnName("donation_referrals");

                    b.Property<double?>("EngagementRate")
                        .HasColumnType("float")
                        .HasColumnName("engagement_rate");

                    b.Property<double?>("EstimatedDonationValuePhp")
                        .HasColumnType("float")
                        .HasColumnName("estimated_donation_value_php");

                    b.Property<bool?>("FeaturesResidentStory")
                        .HasColumnType("bit")
                        .HasColumnName("features_resident_story");

                    b.Property<int?>("FollowerCountAtPost")
                        .HasColumnType("int")
                        .HasColumnName("follower_count_at_post");

                    b.Property<int?>("Forwards")
                        .HasColumnType("int")
                        .HasColumnName("forwards");

                    b.Property<bool?>("HasCallToAction")
                        .HasColumnType("bit")
                        .HasColumnName("has_call_to_action");

                    b.Property<string>("Hashtags")
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("hashtags");

                    b.Property<int?>("Impressions")
                        .HasColumnType("int")
                        .HasColumnName("impressions");

                    b.Property<bool?>("IsBoosted")
                        .HasColumnType("bit")
                        .HasColumnName("is_boosted");

                    b.Property<int?>("Likes")
                        .HasColumnType("int")
                        .HasColumnName("likes");

                    b.Property<string>("MediaType")
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("media_type");

                    b.Property<int?>("MentionsCount")
                        .HasColumnType("int")
                        .HasColumnName("mentions_count");

                    b.Property<int?>("NumHashtags")
                        .HasColumnType("int")
                        .HasColumnName("num_hashtags");

                    b.Property<string>("Platform")
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("platform");

                    b.Property<string>("PlatformPostId")
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("platform_post_id");

                    b.Property<int?>("PostHour")
                        .HasColumnType("int")
                        .HasColumnName("post_hour");

                    b.Property<string>("PostType")
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("post_type");

                    b.Property<string>("PostUrl")
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("post_url");

                    b.Property<int?>("ProfileVisits")
                        .HasColumnType("int")
                        .HasColumnName("profile_visits");

                    b.Property<int?>("Reach")
                        .HasColumnType("int")
                        .HasColumnName("reach");

                    b.Property<int?>("Saves")
                        .HasColumnType("int")
                        .HasColumnName("saves");

                    b.Property<string>("SentimentTone")
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("sentiment_tone");

                    b.Property<int?>("Shares")
                        .HasColumnType("int")
                        .HasColumnName("shares");

                    b.Property<int?>("SubscriberCountAtPost")
                        .HasColumnType("int")
                        .HasColumnName("subscriber_count_at_post");

                    b.Property<int?>("VideoViews")
                        .HasColumnType("int")
                        .HasColumnName("video_views");

                    b.Property<int?>("WatchTimeSeconds")
                        .HasColumnType("int")
                        .HasColumnName("watch_time_seconds");

                    b.HasKey("PostId");

                    b.ToTable("social_media_posts", (string)null);
                });

            modelBuilder.Entity("HirayaHaven.Api.Models.Staff", b =>
                {
                    b.Property<int>("StaffId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("staff_id");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("StaffId"));

                    b.Property<int?>("Age")
                        .HasColumnType("int")
                        .HasColumnName("age");

                    b.Property<string>("CreatedAt")
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("created_at");

                    b.Property<string>("DateEnded")
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("date_ended");

                    b.Property<string>("DateHired")
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("date_hired");

                    b.Property<string>("Email")
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("email");

                    b.Property<string>("EmploymentStatus")
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("employment_status");

                    b.Property<string>("EmploymentType")
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("employment_type");

                    b.Property<string>("FirstName")
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("first_name");

                    b.Property<string>("LastName")
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("last_name");

                    b.Property<string>("Phone")
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("phone");

                    b.Property<string>("Role")
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("role");

                    b.Property<int?>("SafehouseId")
                        .HasColumnType("int")
                        .HasColumnName("safehouse_id");

                    b.Property<string>("Specialization")
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("specialization");

                    b.Property<string>("StaffCode")
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("staff_code");

                    b.Property<string>("UpdatedAt")
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("updated_at");

                    b.HasKey("StaffId");

                    b.HasIndex("SafehouseId");

                    b.ToTable("staff", (string)null);
                });

            modelBuilder.Entity("HirayaHaven.Api.Models.Supporter", b =>
                {
                    b.Property<int>("SupporterId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("supporter_id");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("SupporterId"));

                    b.Property<string>("AcquisitionChannel")
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("acquisition_channel");

                    b.Property<string>("Country")
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("country");

                    b.Property<string>("CreatedAt")
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("created_at");

                    b.Property<string>("DisplayName")
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("display_name");

                    b.Property<string>("Email")
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("email");

                    b.Property<string>("FirstDonationDate")
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("first_donation_date");

                    b.Property<string>("FirstName")
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("first_name");

                    b.Property<string>("LastName")
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("last_name");

                    b.Property<string>("OrganizationName")
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("organization_name");

                    b.Property<string>("Phone")
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("phone");

                    b.Property<string>("Region")
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("region");

                    b.Property<string>("RelationshipType")
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("relationship_type");

                    b.Property<string>("Status")
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("status");

                    b.Property<string>("SupporterType")
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("supporter_type");

                    b.HasKey("SupporterId");

                    b.ToTable("supporters", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityRole<int>", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("ConcurrencyStamp")
                        .IsConcurrencyToken()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Name")
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.Property<string>("NormalizedName")
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.HasKey("Id");

                    b.HasIndex("NormalizedName")
                        .IsUnique()
                        .HasDatabaseName("RoleNameIndex")
                        .HasFilter("[NormalizedName] IS NOT NULL");

                    b.ToTable("AspNetRoles", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityRoleClaim<int>", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("ClaimType")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ClaimValue")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("RoleId")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("RoleId");

                    b.ToTable("AspNetRoleClaims", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserClaim<int>", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("ClaimType")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ClaimValue")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("UserId")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("UserId");

                    b.ToTable("AspNetUserClaims", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserLogin<int>", b =>
                {
                    b.Property<string>("LoginProvider")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("ProviderKey")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("ProviderDisplayName")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("UserId")
                        .HasColumnType("int");

                    b.HasKey("LoginProvider", "ProviderKey");

                    b.HasIndex("UserId");

                    b.ToTable("AspNetUserLogins", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserRole<int>", b =>
                {
                    b.Property<int>("UserId")
                        .HasColumnType("int");

                    b.Property<int>("RoleId")
                        .HasColumnType("int");

                    b.HasKey("UserId", "RoleId");

                    b.HasIndex("RoleId");

                    b.ToTable("AspNetUserRoles", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserToken<int>", b =>
                {
                    b.Property<int>("UserId")
                        .HasColumnType("int");

                    b.Property<string>("LoginProvider")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("Name")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("Value")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("UserId", "LoginProvider", "Name");

                    b.ToTable("AspNetUserTokens", (string)null);
                });

            modelBuilder.Entity("HirayaHaven.Api.Models.AppUser", b =>
                {
                    b.HasOne("HirayaHaven.Api.Models.AppUser", "ApprovedByUser")
                        .WithMany()
                        .HasForeignKey("ApprovedBy")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.HasOne("HirayaHaven.Api.Models.AppUser", "CreatedByUser")
                        .WithMany()
                        .HasForeignKey("CreatedBy")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.HasOne("HirayaHaven.Api.Models.AppUser", "ResetInitiatedByUser")
                        .WithMany()
                        .HasForeignKey("ResetInitiatedBy")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.HasOne("HirayaHaven.Api.Models.Resident", "Resident")
                        .WithMany()
                        .HasForeignKey("ResidentId")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.HasOne("HirayaHaven.Api.Models.Staff", "Staff")
                        .WithMany()
                        .HasForeignKey("StaffId")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.HasOne("HirayaHaven.Api.Models.Supporter", "Supporter")
                        .WithMany()
                        .HasForeignKey("SupporterId")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.Navigation("ApprovedByUser");

                    b.Navigation("CreatedByUser");

                    b.Navigation("ResetInitiatedByUser");

                    b.Navigation("Resident");

                    b.Navigation("Staff");

                    b.Navigation("Supporter");
                });

            modelBuilder.Entity("HirayaHaven.Api.Models.AuditLog", b =>
                {
                    b.HasOne("HirayaHaven.Api.Models.AppUser", "ApprovedByUser")
                        .WithMany()
                        .HasForeignKey("ApprovedBy")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.HasOne("HirayaHaven.Api.Models.AppUser", "User")
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("ApprovedByUser");

                    b.Navigation("User");
                });

            modelBuilder.Entity("HirayaHaven.Api.Models.Donation", b =>
                {
                    b.HasOne("HirayaHaven.Api.Models.SocialMediaPost", "ReferralPost")
                        .WithMany("ReferralDonations")
                        .HasForeignKey("ReferralPostId")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.HasOne("HirayaHaven.Api.Models.Supporter", "Supporter")
                        .WithMany("Donations")
                        .HasForeignKey("SupporterId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("ReferralPost");

                    b.Navigation("Supporter");
                });

            modelBuilder.Entity("HirayaHaven.Api.Models.DonationAllocation", b =>
                {
                    b.HasOne("HirayaHaven.Api.Models.Donation", "Donation")
                        .WithMany("DonationAllocations")
                        .HasForeignKey("DonationId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("HirayaHaven.Api.Models.Safehouse", "Safehouse")
                        .WithMany("DonationAllocations")
                        .HasForeignKey("SafehouseId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Donation");

                    b.Navigation("Safehouse");
                });

            modelBuilder.Entity("HirayaHaven.Api.Models.EducationRecord", b =>
                {
                    b.HasOne("HirayaHaven.Api.Models.Resident", "Resident")
                        .WithMany("EducationRecords")
                        .HasForeignKey("ResidentId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Resident");
                });

            modelBuilder.Entity("HirayaHaven.Api.Models.HealthWellbeingRecord", b =>
                {
                    b.HasOne("HirayaHaven.Api.Models.Resident", "Resident")
                        .WithMany("HealthWellbeingRecords")
                        .HasForeignKey("ResidentId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Resident");
                });

            modelBuilder.Entity("HirayaHaven.Api.Models.HomeVisitation", b =>
                {
                    b.HasOne("HirayaHaven.Api.Models.Resident", "Resident")
                        .WithMany("HomeVisitations")
                        .HasForeignKey("ResidentId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Resident");
                });

            modelBuilder.Entity("HirayaHaven.Api.Models.InKindDonationItem", b =>
                {
                    b.HasOne("HirayaHaven.Api.Models.Donation", "Donation")
                        .WithMany("InKindDonationItems")
                        .HasForeignKey("DonationId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Donation");
                });

            modelBuilder.Entity("HirayaHaven.Api.Models.IncidentReport", b =>
                {
                    b.HasOne("HirayaHaven.Api.Models.Resident", "Resident")
                        .WithMany("IncidentReports")
                        .HasForeignKey("ResidentId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("HirayaHaven.Api.Models.Safehouse", "Safehouse")
                        .WithMany("IncidentReports")
                        .HasForeignKey("SafehouseId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Resident");

                    b.Navigation("Safehouse");
                });

            modelBuilder.Entity("HirayaHaven.Api.Models.InterventionPlan", b =>
                {
                    b.HasOne("HirayaHaven.Api.Models.Resident", "Resident")
                        .WithMany("InterventionPlans")
                        .HasForeignKey("ResidentId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Resident");
                });

            modelBuilder.Entity("HirayaHaven.Api.Models.PartnerAssignment", b =>
                {
                    b.HasOne("HirayaHaven.Api.Models.Partner", "Partner")
                        .WithMany("PartnerAssignments")
                        .HasForeignKey("PartnerId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("HirayaHaven.Api.Models.Safehouse", "Safehouse")
                        .WithMany("PartnerAssignments")
                        .HasForeignKey("SafehouseId")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.Navigation("Partner");

                    b.Navigation("Safehouse");
                });

            modelBuilder.Entity("HirayaHaven.Api.Models.ProcessRecording", b =>
                {
                    b.HasOne("HirayaHaven.Api.Models.Resident", "Resident")
                        .WithMany("ProcessRecordings")
                        .HasForeignKey("ResidentId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Resident");
                });

            modelBuilder.Entity("HirayaHaven.Api.Models.Resident", b =>
                {
                    b.HasOne("HirayaHaven.Api.Models.Safehouse", "Safehouse")
                        .WithMany("Residents")
                        .HasForeignKey("SafehouseId")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.Navigation("Safehouse");
                });

            modelBuilder.Entity("HirayaHaven.Api.Models.SafehouseMonthlyMetric", b =>
                {
                    b.HasOne("HirayaHaven.Api.Models.Safehouse", "Safehouse")
                        .WithMany("SafehouseMonthlyMetrics")
                        .HasForeignKey("SafehouseId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Safehouse");
                });

            modelBuilder.Entity("HirayaHaven.Api.Models.Staff", b =>
                {
                    b.HasOne("HirayaHaven.Api.Models.Safehouse", "Safehouse")
                        .WithMany("StaffMembers")
                        .HasForeignKey("SafehouseId")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.Navigation("Safehouse");
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityRoleClaim<int>", b =>
                {
                    b.HasOne("Microsoft.AspNetCore.Identity.IdentityRole<int>", null)
                        .WithMany()
                        .HasForeignKey("RoleId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserClaim<int>", b =>
                {
                    b.HasOne("HirayaHaven.Api.Models.AppUser", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserLogin<int>", b =>
                {
                    b.HasOne("HirayaHaven.Api.Models.AppUser", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserRole<int>", b =>
                {
                    b.HasOne("Microsoft.AspNetCore.Identity.IdentityRole<int>", null)
                        .WithMany()
                        .HasForeignKey("RoleId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("HirayaHaven.Api.Models.AppUser", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserToken<int>", b =>
                {
                    b.HasOne("HirayaHaven.Api.Models.AppUser", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("HirayaHaven.Api.Models.Donation", b =>
                {
                    b.Navigation("DonationAllocations");

                    b.Navigation("InKindDonationItems");
                });

            modelBuilder.Entity("HirayaHaven.Api.Models.Partner", b =>
                {
                    b.Navigation("PartnerAssignments");
                });

            modelBuilder.Entity("HirayaHaven.Api.Models.Resident", b =>
                {
                    b.Navigation("EducationRecords");

                    b.Navigation("HealthWellbeingRecords");

                    b.Navigation("HomeVisitations");

                    b.Navigation("IncidentReports");

                    b.Navigation("InterventionPlans");

                    b.Navigation("ProcessRecordings");
                });

            modelBuilder.Entity("HirayaHaven.Api.Models.Safehouse", b =>
                {
                    b.Navigation("DonationAllocations");

                    b.Navigation("IncidentReports");

                    b.Navigation("PartnerAssignments");

                    b.Navigation("Residents");

                    b.Navigation("SafehouseMonthlyMetrics");

                    b.Navigation("StaffMembers");
                });

            modelBuilder.Entity("HirayaHaven.Api.Models.SocialMediaPost", b =>
                {
                    b.Navigation("ReferralDonations");
                });

            modelBuilder.Entity("HirayaHaven.Api.Models.Supporter", b =>
                {
                    b.Navigation("Donations");
                });
#pragma warning restore 612, 618
        }
    }
}
